# Generated by Django 4.2.11 on 2024-04-28 16:14

from django.db import migrations
import oauth2_provider.generators
import oauth2_provider.models


class Migration(migrations.Migration):

    dependencies = [
        ('dab_oauth2_provider', '0003_alter_oauth2accesstoken_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth2application',
            name='client_secret',
            field=oauth2_provider.models.ClientSecretField(blank=True, db_index=True, default=oauth2_provider.generators.generate_client_secret, help_text='Hashed on Save. Copy it now if this is a new secret.', max_length=255),
        ),
    ]
