# Generated by Django 5.2.9 on 2026-03-10 18:02

import ansible_base.oauth2_provider.models.access_token
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dab_oauth2_provider', '0008_oauth2application_app_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth2accesstoken',
            name='scope',
            field=models.CharField(default='write', help_text="Allowed scopes, further restricts user permissions. Must be a simple space-separated string with allowed scopes ['read', 'write', 'openid', 'roles'].", max_length=128, validators=[ansible_base.oauth2_provider.models.access_token.validate_scope]),
        ),
    ]
