#  Copyright 2024 Red Hat, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# Generated by Django 4.2.8 on 2024-03-11 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dab_authentication', '0003_alter_authenticatormap_authenticator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authenticator',
            old_name='created_on',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='authenticator',
            old_name='modified_on',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='authenticatormap',
            old_name='created_on',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='authenticatormap',
            old_name='modified_on',
            new_name='modified',
        ),
        migrations.AlterField(
            model_name='authenticator',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date/time this resource was created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authenticator',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The date/time this resource was created'),
        ),
        migrations.AlterField(
            model_name='authenticatormap',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date/time this resource was created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authenticatormap',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The date/time this resource was created'),
        ),
    ]
