# Generated by Django 4.2.11 on 2024-05-21 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dab_rbac', '__first__'),
        ('dab_authentication', '0010_alter_authenticatoruser_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticatormap',
            name='role',
            field=models.ForeignKey(help_text='The role this mapping belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authenticator_maps', to='dab_rbac.roledefinition'),
        ),
        migrations.AlterField(
            model_name='authenticatormap',
            name='map_type',
            field=models.CharField(
                choices=[('allow', 'allow'), ('is_superuser', 'is_superuser'), ('organization', 'organization'),
                         ('team', 'team'), ('role', 'role')], default='team',
                help_text='What does the map work on, a team, organization, a user flag or is this an allow rule',
                max_length=17),
        ),
    ]
