# Generated by Django 4.2.11 on 2024-06-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dab_authentication', '0012_alter_authenticatormap_map_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticatormap',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Enables or disables this authentication map', null=False),
        ),
    ]
