# Generated by Django 4.2.14 on 2024-09-02 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dab_authentication', '0013_alter_authenticator_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticator',
            name='auto_migrate_users_to',
            field=models.ForeignKey(help_text='Automatically move users from this authenticator to the target authenticator when a matching user logs in via the targe authenticator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_migrate_users_from', to='dab_authentication.authenticator'),
        ),
    ]
