# Generated by Django 4.2.11 on 2024-08-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dab_authentication', '0013_alter_authenticator_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticatoruser',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
