# Generated by Django 4.2.21 on 2025-07-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dab_authentication', '0017_alter_authenticator_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticatoruser',
            name='email',
            field=models.EmailField(blank=True, default=None, help_text='The e-mail associated with this authenticator user.', max_length=254, null=True),
        ),
    ]
