# Generated by Django 4.2.16 on 2026-10-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dab_authentication', '0018_authenticatoruser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticator',
            name='create_objects',
            field=models.BooleanField(
                default=True,
                help_text='Allow authenticator to create Organizations and Teams through authenticator maps.',
            ),
        ),
    ]
