# Generated by Claude Sonnet 4

import os
import time

import pytest
from django.db import connection

from ansible_base.rbac.models import DABContentType, DABPermission, RoleDefinition
from test_app.models import Organization, Team, User


class TestSummaryFieldsPerformance:
    """
    Test that summary fields with prefetch_related don't cause N+1 query issues.
    """

    def test_summary_fields_with_prefetch_related_performance(self, db):
        """
        Test that accessing summary fields on multiple organizations with
        prefetch_related('resource') doesn't trigger additional queries after the first organization.
        """
        # Create multiple organizations
        orgs = []
        for i in range(5):
            org = Organization.objects.create(name=f'Org {i}', description=f'Description for org {i}')
            orgs.append(org)

        # Query organizations with prefetch_related
        organizations = Organization.objects.prefetch_related('resource', 'modified_by', 'created_by').all()

        # Reset query count before the test
        connection.queries_log.clear()

        # Access get_summary_fields for each organization
        for i, org in enumerate(organizations):
            queries_before = len(connection.queries_log)
            org.get_summary_fields()
            queries_after = len(connection.queries_log)
            queries_for_this_org = queries_after - queries_before

            # With comprehensive prefetching (resource, modified_by, created_by),
            # all items should trigger 0 queries for get_summary_fields()
            assert queries_for_this_org == 0, (
                f"Organization {i} triggered {queries_for_this_org} queries. " f"With comprehensive prefetching, expected 0 queries for all items."
            )

    def test_summary_fields_detailed_query_analysis(self, db):
        """
        More detailed test that tracks exactly when queries are executed.
        """
        # Create organizations
        orgs = []
        for i in range(3):
            org = Organization.objects.create(name=f'Org {i}', description=f'Description for org {i}')
            orgs.append(org)

        # Query with prefetch_related
        organizations = Organization.objects.prefetch_related('resource', 'modified_by', 'created_by').all()

        connection.queries_log.clear()

        summary_fields_list = []
        query_counts = []

        for i, org in enumerate(organizations):
            queries_before = len(connection.queries_log)
            summary_fields = org.get_summary_fields()
            queries_after = len(connection.queries_log)
            queries_for_this_org = queries_after - queries_before

            summary_fields_list.append(summary_fields)
            query_counts.append(queries_for_this_org)

        # Check query counts per organization
        for i, queries_for_this_org in enumerate(query_counts):
            # With proper prefetch_related, all items should trigger 0 queries
            assert queries_for_this_org == 0, (
                f"Organization {i} triggered {queries_for_this_org} queries. "
                f"Query counts per org: {query_counts}. "
                f"With prefetch_related('resource'), expected 0 queries for all items."
            )

    def test_summary_fields_with_additional_prefetches(self, db):
        """
        Test with additional prefetches that might be needed for summary fields.
        """
        # Create organizations
        orgs = []
        for i in range(3):
            org = Organization.objects.create(name=f'Org {i}', description=f'Description for org {i}')
            orgs.append(org)

        # Query with minimal prefetches - internal caching handles deeper relationships
        organizations = Organization.objects.prefetch_related('resource', 'modified_by', 'created_by').all()

        connection.queries_log.clear()

        # Access summary fields for each organization
        for i, org in enumerate(organizations):
            queries_before = len(connection.queries_log)
            org.get_summary_fields()
            queries_after = len(connection.queries_log)
            queries_for_this_org = queries_after - queries_before

            # With minimal prefetching + internal caching, all items should trigger 0 queries
            assert queries_for_this_org == 0, (
                f"Organization {i} triggered {queries_for_this_org} queries. " f"With minimal prefetching, expected 0 queries for all items."
            )

    @pytest.mark.django_db
    def test_summary_fields_content_verification(self):
        """
        Verify that summary fields actually contain the expected resource information.
        """
        # Create an organization
        org = Organization.objects.create(name='Test Org', description='Test Description')

        # Get summary fields
        summary_fields = org.get_summary_fields()

        # Verify that resource information is included
        assert 'resource' in summary_fields

        # The resource should have summary fields too
        resource_summary = summary_fields['resource']
        assert 'ansible_id' in resource_summary
        assert 'resource_type' in resource_summary


class TestRoleDefinitionSummaryFieldsPerformance:
    """
    Test that RoleDefinition summary fields with prefetch_related don't cause N+1 query issues.
    """

    def get_roledefinition_count(self):
        """
        Determine how many RoleDefinitions to create based on environment variables.
        Uses same pattern as create_demo_data command.
        """
        if os.environ.get('LARGE'):
            # Use a substantial number for performance testing, but not as many as other models
            # since RoleDefinitions are typically fewer in number but more complex
            return 100
        else:
            # Small number for regular tests
            return 5

    def test_roledefinition_summary_fields_with_prefetch_related_performance(self, db):
        """
        Test that accessing summary fields on multiple RoleDefinitions with
        prefetch_related('resource') doesn't trigger additional queries after the first RoleDefinition.
        """
        # Create multiple role definitions with permissions
        role_definitions = []
        count = self.get_roledefinition_count()

        # Create a content type for permissions
        org_ct = DABContentType.objects.get_for_model(Organization)

        print(f"\nCreating {count} RoleDefinitions for performance testing...")
        for i in range(count):
            # Create some sample permissions
            perm1 = DABPermission.objects.create(name=f'Can view role {i}', codename=f'view_role_{i}', content_type=org_ct)
            perm2 = DABPermission.objects.create(name=f'Can edit role {i}', codename=f'edit_role_{i}', content_type=org_ct)

            # Create role definition
            rd = RoleDefinition.objects.create(name=f'Role Definition {i}', description=f'Description for role definition {i}')

            # Add permissions to the role definition
            rd.permissions.add(perm1, perm2)
            role_definitions.append(rd)

        # Query role definitions with prefetch_related (including permissions)
        role_definitions_qs = RoleDefinition.objects.prefetch_related('resource', 'modified_by', 'created_by', 'permissions').all()

        # Reset query count before the test
        connection.queries_log.clear()

        # Access summary fields for each role definition with timing
        start_time = time.time()
        for i, rd in enumerate(role_definitions_qs):
            queries_before = len(connection.queries_log)
            rd.summary_fields()
            queries_after = len(connection.queries_log)
            queries_for_this_rd = queries_after - queries_before

            # With proper prefetch_related, all items should trigger 0 queries
            assert queries_for_this_rd == 0, (
                f"RoleDefinition {i} triggered {queries_for_this_rd} queries. " f"With prefetch_related('resource'), expected 0 queries for all items."
            )

        elapsed_time = time.time() - start_time
        print(f"Processed {count} RoleDefinitions in {elapsed_time:.3f} seconds ({count/elapsed_time:.1f} items/sec)")

    def test_roledefinition_summary_fields_with_additional_prefetches(self, db):
        """
        Test RoleDefinitions with comprehensive prefetching including resource relationships.
        """
        # Create role definitions with permissions
        role_definitions = []
        count = self.get_roledefinition_count()

        # Create a content type for permissions
        org_ct = DABContentType.objects.get_for_model(Organization)

        print(f"\nCreating {count} RoleDefinitions with additional prefetches...")
        for i in range(count):
            # Create sample permissions
            perm1 = DABPermission.objects.create(name=f'Can manage role {i}', codename=f'manage_role_{i}', content_type=org_ct)
            perm2 = DABPermission.objects.create(name=f'Can delete role {i}', codename=f'delete_role_{i}', content_type=org_ct)
            perm3 = DABPermission.objects.create(name=f'Can assign role {i}', codename=f'assign_role_{i}', content_type=org_ct)

            # Create role definition
            rd = RoleDefinition.objects.create(name=f'Role Definition {i}', description=f'Description for role definition {i}')

            # Add permissions to the role definition
            rd.permissions.add(perm1, perm2, perm3)
            role_definitions.append(rd)

        # Query with minimal prefetches - internal caching handles deeper relationships
        role_definitions_qs = RoleDefinition.objects.prefetch_related('resource', 'modified_by', 'created_by', 'permissions').all()

        connection.queries_log.clear()

        # Access summary fields for each role definition
        for i, rd in enumerate(role_definitions_qs):
            queries_before = len(connection.queries_log)
            rd.summary_fields()
            queries_after = len(connection.queries_log)
            queries_for_this_rd = queries_after - queries_before

            # With minimal prefetching + internal caching, all items should trigger 0 queries
            assert queries_for_this_rd == 0, (
                f"RoleDefinition {i} triggered {queries_for_this_rd} queries. " f"With minimal prefetching, expected 0 queries for all items."
            )

    @pytest.mark.django_db
    def test_roledefinition_summary_fields_content_verification(self):
        """
        Verify that RoleDefinition summary fields contain the expected information.
        """
        # Create a role definition
        rd = RoleDefinition.objects.create(name='Test Role Definition', description='Test Description')

        # Get summary fields
        summary_fields = rd.summary_fields()

        # Verify expected fields are present
        assert 'id' in summary_fields
        assert 'name' in summary_fields
        assert 'description' in summary_fields
        assert 'managed' in summary_fields
        assert summary_fields['name'] == 'Test Role Definition'
        assert summary_fields['description'] == 'Test Description'


class TestUserSummaryFieldsPerformance:
    """
    Test that User summary fields with prefetch_related don't cause N+1 query issues.
    """

    def test_user_summary_fields_with_prefetch_related_performance(self, db):
        """
        Test that accessing summary fields on multiple Users with
        prefetch_related('resource') doesn't trigger additional queries after the first User.
        """
        # Create multiple users
        users = []
        for i in range(5):
            user = User.objects.create(username=f'user{i}', email=f'user{i}@example.com')
            users.append(user)

        # Query users with prefetch_related
        users_qs = User.objects.prefetch_related('resource', 'modified_by', 'created_by').all()

        # Reset query count before the test
        connection.queries_log.clear()

        # Access summary fields for each user
        for i, user in enumerate(users_qs):
            queries_before = len(connection.queries_log)
            user.summary_fields()
            queries_after = len(connection.queries_log)
            queries_for_this_user = queries_after - queries_before

            # With proper prefetch_related, all items should trigger 0 queries
            assert queries_for_this_user == 0, (
                f"User {i} triggered {queries_for_this_user} queries. " f"With prefetch_related('resource'), expected 0 queries for all items."
            )

    def test_user_summary_fields_with_additional_prefetches(self, db):
        """
        Test Users with comprehensive prefetching including resource relationships.
        """
        # Create users
        users = []
        for i in range(3):
            user = User.objects.create(username=f'user{i}', email=f'user{i}@example.com')
            users.append(user)

        # Query with minimal prefetches - internal caching handles deeper relationships
        users_qs = User.objects.prefetch_related('resource', 'modified_by', 'created_by').all()

        connection.queries_log.clear()

        # Access summary fields for each user
        for i, user in enumerate(users_qs):
            queries_before = len(connection.queries_log)
            user.summary_fields()
            queries_after = len(connection.queries_log)
            queries_for_this_user = queries_after - queries_before

            # With minimal prefetching + internal caching, all items should trigger 0 queries
            assert queries_for_this_user == 0, (
                f"User {i} triggered {queries_for_this_user} queries. " f"With minimal prefetching, expected 0 queries for all items."
            )


class TestTeamSummaryFieldsPerformance:
    """
    Test that Team summary fields with prefetch_related don't cause N+1 query issues.
    """

    def test_team_summary_fields_with_prefetch_related_performance(self, db):
        """
        Test that accessing summary fields on multiple Teams with
        prefetch_related('resource') doesn't trigger additional queries after the first Team.
        """
        # Create an organization first (required for teams)
        org = Organization.objects.create(name='Test Org', description='Test Description')

        # Create multiple teams
        teams = []
        for i in range(5):
            team = Team.objects.create(name=f'Team {i}', organization=org)
            teams.append(team)

        # Query teams with prefetch_related
        teams_qs = Team.objects.prefetch_related('resource', 'organization', 'modified_by', 'created_by').all()

        # Reset query count before the test
        connection.queries_log.clear()

        # Access summary fields for each team
        for i, team in enumerate(teams_qs):
            queries_before = len(connection.queries_log)
            team.summary_fields()
            queries_after = len(connection.queries_log)
            queries_for_this_team = queries_after - queries_before

            # With proper prefetch_related, all items should trigger 0 queries
            assert queries_for_this_team == 0, (
                f"Team {i} triggered {queries_for_this_team} queries. " f"With prefetch_related('resource'), expected 0 queries for all items."
            )

    def test_team_summary_fields_with_additional_prefetches(self, db):
        """
        Test Teams with comprehensive prefetching including resource and organization relationships.
        """
        # Create an organization first
        org = Organization.objects.create(name='Test Org', description='Test Description')

        # Create teams
        teams = []
        for i in range(3):
            team = Team.objects.create(name=f'Team {i}', organization=org)
            teams.append(team)

        # Query with minimal prefetches - internal caching handles deeper relationships
        teams_qs = Team.objects.prefetch_related('resource', 'organization', 'modified_by', 'created_by').all()

        connection.queries_log.clear()

        # Access summary fields for each team
        for i, team in enumerate(teams_qs):
            queries_before = len(connection.queries_log)
            team.summary_fields()
            queries_after = len(connection.queries_log)
            queries_for_this_team = queries_after - queries_before

            # With minimal prefetching + internal caching, all items should trigger 0 queries
            assert queries_for_this_team == 0, (
                f"Team {i} triggered {queries_for_this_team} queries. " f"With minimal prefetching, expected 0 queries for all items."
            )

    @pytest.mark.django_db
    def test_team_summary_fields_content_verification(self):
        """
        Verify that Team summary fields contain the expected information.
        """
        # Create an organization and team
        org = Organization.objects.create(name='Test Org', description='Test Description')
        team = Team.objects.create(name='Test Team', organization=org)

        # Get summary fields using get_summary_fields which includes related fields
        summary_fields = team.get_summary_fields()

        # Verify expected fields are present
        assert 'id' in summary_fields or hasattr(team, 'id')
        # Verify organization information is included (if it's in get_summary_fields)
        if 'organization' in summary_fields:
            org_summary = summary_fields['organization']
            assert 'id' in org_summary
            assert 'name' in org_summary
            assert org_summary['name'] == 'Test Org'

        # Also test the basic summary_fields method
        basic_summary = team.summary_fields()
        assert 'id' in basic_summary
        assert 'name' in basic_summary
        assert basic_summary['name'] == 'Test Team'


class TestCombinedModelsSummaryFieldsPerformance:
    """
    Test summary fields performance across multiple model types in the same test.
    """

    @pytest.mark.django_db
    def test_mixed_models_summary_fields_performance(self):
        """
        Test accessing summary fields on multiple different model types to ensure
        consistent performance patterns across all resource registry models.
        """
        # Create test data
        org = Organization.objects.create(name='Test Org', description='Test Description')

        users = []
        for i in range(3):
            user = User.objects.create(username=f'user{i}', email=f'user{i}@example.com')
            users.append(user)

        teams = []
        for i in range(3):
            team = Team.objects.create(name=f'Team {i}', organization=org)
            teams.append(team)

        # Create role definitions with permissions
        role_definitions = []
        org_ct = DABContentType.objects.get_for_model(Organization)

        # Use smaller count for combined test to keep it manageable
        rd_count = 100 if os.environ.get('LARGE') else 3
        print(f"\nCreating {rd_count} RoleDefinitions for combined test...")

        for i in range(rd_count):
            # Create permissions for this role definition
            perm1 = DABPermission.objects.create(name=f'Can view resource {i}', codename=f'view_resource_{i}', content_type=org_ct)
            perm2 = DABPermission.objects.create(name=f'Can edit resource {i}', codename=f'edit_resource_{i}', content_type=org_ct)

            rd = RoleDefinition.objects.create(name=f'Role Definition {i}', description=f'Description for role definition {i}')
            rd.permissions.add(perm1, perm2)
            role_definitions.append(rd)

        # Test each model type with minimal prefetching
        models_and_queries = [
            (Organization.objects.prefetch_related('resource', 'modified_by', 'created_by'), 'Organization'),
            (User.objects.prefetch_related('resource', 'modified_by', 'created_by'), 'User'),
            (Team.objects.prefetch_related('resource', 'organization', 'modified_by', 'created_by'), 'Team'),
            (RoleDefinition.objects.prefetch_related('resource', 'modified_by', 'created_by', 'permissions'), 'RoleDefinition'),
        ]

        for queryset, model_name in models_and_queries:
            connection.queries_log.clear()

            for i, instance in enumerate(queryset.all()):
                queries_before = len(connection.queries_log)
                instance.summary_fields()
                queries_after = len(connection.queries_log)
                queries_for_this_instance = queries_after - queries_before

                # With proper prefetching, all items should trigger 0 queries
                assert queries_for_this_instance == 0, (
                    f"{model_name} {i} triggered {queries_for_this_instance} queries. " f"With proper prefetching, expected 0 queries for all items."
                )
