# Generated by Claude Sonnet 4

import uuid
from unittest import mock

import pytest
from django.test.utils import override_settings

from ansible_base.lib.utils.response import get_relative_url

# Make fixture available
from test_app.tests.resource_registry.conftest import enable_reverse_sync  # noqa: F401


@pytest.mark.django_db
def test_roledefinition_create_with_permissions_reverse_sync(admin_api_client, enable_reverse_sync):  # noqa: F811
    """
    Test that creating a RoleDefinition with permissions triggers reverse-sync correctly.

    This test verifies that the delayed reverse-sync fix works properly.
    With the fix, permissions should be included in the sync data instead of being empty.
    """

    # Enable reverse-sync and mock the resource server client's _make_request method
    with enable_reverse_sync():
        with override_settings(RESOURCE_SERVER={'URL': 'http://example.invalid', 'SECRET_KEY': 'test-secret-key'}):
            with mock.patch('ansible_base.resource_registry.rest_client.ResourceAPIClient._make_request') as mock_make_request:
                # Mock successful response from resource server
                mock_response = mock.Mock()
                mock_response.status_code = 201
                mock_response.json.return_value = {'ansible_id': str(uuid.uuid4()), 'service_id': str(uuid.uuid4())}
                mock_make_request.return_value = mock_response

                # Create RoleDefinition via API (this should trigger reverse-sync)
                url = get_relative_url("roledefinition-list")
                data = {
                    'name': 'test-reverse-sync-role',
                    'description': 'Test role for reverse sync',
                    'permissions': ['shared.view_organization', 'shared.change_organization'],
                    'content_type': 'shared.organization',
                }

                response = admin_api_client.post(url, data=data, format="json")
                assert response.status_code == 201, f"Failed to create role: {response.data}"

                # Verify that _make_request was called (meaning reverse-sync was attempted)
                assert mock_make_request.called, "Resource server sync should have been called"

                # Find the POST request that creates the resource
                create_calls = [call for call in mock_make_request.call_args_list if call[0][0].upper() == 'POST']  # First arg is HTTP method

                assert len(create_calls) >= 1, (
                    f"Should have at least one POST call to create resource. " f"Found calls: {[call[0] for call in mock_make_request.call_args_list]}"
                )

                # Get the request data from the create call
                create_call = create_calls[0]
                # The call structure is: (method, url, data)
                request_data = create_call[0][2]  # Third positional argument is the data

                # Extract the resource_data that would be sent to the resource server
                resource_data = request_data.get('resource_data', {})
                permissions_in_sync = resource_data.get('permissions', [])

                # This should now PASS because the delayed sync ensures permissions are included
                # The fix ensures that permissions are no longer empty during sync
                expected_permissions = {'shared.view_organization', 'shared.change_organization'}
                actual_permissions = set(permissions_in_sync)
                assert actual_permissions == expected_permissions, (
                    f"Expected permissions {expected_permissions} in reverse-sync data, "
                    f"but got {actual_permissions}. The delayed sync fix should include permissions!"
                )
