import pytest
from django.apps import apps

from ansible_base.rbac.migrations._utils import cleanup_orphaned_permissions, give_permissions
from ansible_base.rbac.models import DABContentType, DABPermission, RoleDefinition, RoleTeamAssignment, RoleUserAssignment
from ansible_base.rbac.permission_registry import permission_registry
from test_app.models import Team, User


@pytest.mark.django_db
def test_give_permissions(organization, inventory, inv_rd):
    user = User.objects.create(username='user')
    team = Team.objects.create(name='ateam', organization=organization)
    give_permissions(apps, inv_rd, users=[user], teams=[team], object_id=inventory.id, content_type_id=DABContentType.objects.get_for_model(inventory).id)
    assert RoleUserAssignment.objects.filter(user=user).exists()
    assert RoleTeamAssignment.objects.filter(team=team).exists()

    # Make sure it can be ran twice
    give_permissions(apps, inv_rd, users=[user], teams=[team], object_id=inventory.id, content_type_id=DABContentType.objects.get_for_model(inventory).id)


@pytest.mark.django_db
def test_give_permissions_by_id(organization, inventory, inv_rd):
    team = Team.objects.create(name='ateam', organization=organization)
    give_permissions(apps, inv_rd, teams=[team.id], object_id=inventory.id, content_type_id=DABContentType.objects.get_for_model(inventory).id)
    assert RoleTeamAssignment.objects.filter(team=team).exists()

    # Make sure it can be ran twice
    give_permissions(apps, inv_rd, teams=[team.id], object_id=inventory.id, content_type_id=DABContentType.objects.get_for_model(inventory).id)


@pytest.mark.django_db
def test_permission_migration():
    "These are expected to be created via a post_migrate signal just like auth.Permission"
    assert len(DABPermission.objects.order_by('content_type').values_list('content_type').distinct()) == len(permission_registry.all_registered_models)


@pytest.mark.django_db
def test_cleanup_orphaned_permissions_deletes_unregistered_unreferenced():
    """Test that cleanup_orphaned_permissions deletes permissions for unregistered models that are not referenced by any RoleDefinition.

    Generated by Claude Sonnet 4 (claude-sonnet-4@20250514)
    """
    # Create a DABContentType for a model not in the permission registry
    dab_fake_ct = DABContentType.objects.create(app_label='fake_app', model='fakemodel', service='local')

    # Create a permission for this fake model (should be deleted)
    orphaned_permission = DABPermission.objects.create(name='Can view fake model', content_type=dab_fake_ct, codename='view_fakemodel')

    initial_count = DABPermission.objects.count()

    # Run cleanup
    deleted_count = cleanup_orphaned_permissions(apps)

    # Verify the orphaned permission was deleted
    assert deleted_count == 1
    assert DABPermission.objects.count() == initial_count - 1
    assert not DABPermission.objects.filter(id=orphaned_permission.id).exists()


@pytest.mark.django_db
def test_cleanup_orphaned_permissions_preserves_referenced():
    """Test that cleanup_orphaned_permissions preserves permissions for unregistered models that are referenced by RoleDefinitions.

    Generated by Claude Sonnet 4 (claude-sonnet-4@20250514)
    """
    # Create a DABContentType for a model not in the permission registry
    dab_fake_ct = DABContentType.objects.create(app_label='fake_app', model='fakemodel', service='local')

    # Create a permission for this fake model
    referenced_permission = DABPermission.objects.create(name='Can view fake model', content_type=dab_fake_ct, codename='view_fakemodel')

    # Create a RoleDefinition that references this permission
    role_def = RoleDefinition.objects.create(name='Fake Role', content_type=dab_fake_ct)
    role_def.permissions.add(referenced_permission)

    initial_count = DABPermission.objects.count()

    # Run cleanup
    deleted_count = cleanup_orphaned_permissions(apps)

    # Verify the referenced permission was NOT deleted
    assert deleted_count == 0
    assert DABPermission.objects.count() == initial_count
    assert DABPermission.objects.filter(id=referenced_permission.id).exists()
