---
services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: dab_db
      POSTGRES_USER: dab
      POSTGRES_PASSWORD: dabing
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  test_app:
    build:
      context: .
    working_dir: /src
    command: 'test_app/scripts/container_startup.sh'
    volumes:
      - '.:/src'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: dab
      DB_PASSWORD: dabing
