---
services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: dab_db
      POSTGRES_USER: dab
      POSTGRES_PASSWORD: dabing
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "dab", "-d", "dab_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  test_app:
    build:
      context: .
    working_dir: /src
    #command: 'test_app/scripts/container_startup.sh'
    command: './test_app/scripts/container_startup_uwsgi.sh'
    volumes:
      - '.:/src:z'
    ports:
      - '8000:8000'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: dab
      DB_PASSWORD: dabing

  # This is the intermediate application reverse proxy without ssl
  nginx:
    image: "nginx:latest"
    volumes:
      - './compose/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:z'
    ports:
      - '80:80'
    depends_on:
      - test_app

  # This is the ssl terminated "ingress" reverse proxy
  ingress:
    build: ./compose/ingress
    command: './entrypoint.sh'
    volumes:
      - './compose/ingress/certs:/etc/nginx/ssl:z'
    ports:
      - "443:443"
    depends_on:
      - test_app
      - nginx
