#!/usr/bin/env python3
# Generated by Claude Code (Sonnet 4)

"""
Script to test all modules in ansible_base/lib for pure Python compatibility.
This script ensures that modules in the lib folder can be imported without
requiring Django apps to be initialized.
"""

import os
import subprocess
import sys
from pathlib import Path


def find_python_modules(lib_path):
    """Find all Python modules in the lib directory."""
    modules = []
    lib_path = Path(lib_path)

    for py_file in lib_path.rglob("*.py"):
        if py_file.name == "__init__.py":
            # Convert path to module name (including ansible_base prefix)
            relative_path = py_file.parent.relative_to(lib_path.parent.parent)
            module_name = str(relative_path).replace(os.sep, ".")
            modules.append(module_name)
        else:
            # Convert path to module name (including ansible_base prefix)
            relative_path = py_file.relative_to(lib_path.parent.parent)
            module_name = str(relative_path)[:-3].replace(os.sep, ".")  # Remove .py extension
            modules.append(module_name)

    return sorted(modules)


def test_pure_python_import(module_name, base_path):
    """Test if a module can be imported with pure Python (no Django setup)."""
    test_script = f'''
import sys
sys.path.insert(0, "{base_path}")

try:
    import {module_name}
    print("SUCCESS")
except Exception as e:
    print(f"ERROR: {{e}}")
'''

    # Run in a clean environment without Django setup
    env = os.environ.copy()
    if 'DJANGO_SETTINGS_MODULE' in env:
        del env['DJANGO_SETTINGS_MODULE']

    try:
        result = subprocess.run(['python', '-c', test_script], capture_output=True, text=True, env=env, timeout=30)

        if result.returncode == 0 and "SUCCESS" in result.stdout:
            return True, None
        else:
            error_msg = result.stderr.strip() or result.stdout.strip()
            return False, error_msg
    except subprocess.TimeoutExpired:
        return False, "Import test timed out"
    except Exception as e:
        return False, f"Failed to run test: {e}"


def main():
    """Main function to test all modules in ansible_base/lib."""
    script_dir = Path(__file__).parent.parent.parent  # Go up two levels since we're in tools/scripts/
    lib_path = script_dir / "ansible_base" / "lib"

    if not lib_path.exists():
        print(f"ERROR: {lib_path} does not exist")
        sys.exit(1)

    print("Testing pure Python import compatibility for ansible_base/lib modules...")
    print("=" * 70)

    modules = find_python_modules(lib_path)

    # Modules that are allowed to fail because they inherently require Django
    allowed_failures = {
        # Abstract models inherently require Django to be initialized
        'ansible_base.lib.abstract_models',
        'ansible_base.lib.abstract_models.common',
        'ansible_base.lib.abstract_models.immutable',
        'ansible_base.lib.abstract_models.organization',
        'ansible_base.lib.abstract_models.team',
        'ansible_base.lib.abstract_models.user',
        # View classes require Django REST framework
        'ansible_base.lib.utils.views.ansible_base',
        'ansible_base.lib.utils.views.django_app_api',
        'ansible_base.lib.utils.views.permissions',
        'ansible_base.lib.utils.views.urls',
        # Router classes require Django REST framework
        'ansible_base.lib.routers',
        'ansible_base.lib.routers.association_resource_router',
        # These modules require Django settings to be configured at import time
        'ansible_base.lib.backends.prefixed_user_auth',
        'ansible_base.lib.dynamic_config.dynamic_urls',
        'ansible_base.lib.serializers.common',
        'ansible_base.lib.testing.fixtures',
        'ansible_base.lib.testing.util',
        'ansible_base.lib.utils.auth',
    }

    failed_modules = []
    passed_modules = []
    expected_failures = []

    for module_name in modules:
        print(f"Testing {module_name}... ", end="", flush=True)
        success, error = test_pure_python_import(module_name, str(script_dir))

        if success:
            print("✓ PASS")
            passed_modules.append(module_name)
        else:
            if module_name in allowed_failures:
                print("✗ EXPECTED FAIL")
                expected_failures.append((module_name, error))
            else:
                print("✗ UNEXPECTED FAIL")
                print(f"  Error: {error}")
                failed_modules.append((module_name, error))

    print("\n" + "=" * 70)
    print(f"Results: {len(passed_modules)} passed, {len(failed_modules)} unexpected failures, {len(expected_failures)} expected failures")

    if failed_modules:
        print("\nUnexpected failures:")
        for module_name, error in failed_modules:
            print(f"  - {module_name}: {error}")

        print("\nThese modules should be importable with pure Python.")
        print("Consider moving Django-specific imports inline within functions.")
        sys.exit(1)
    else:
        print("\nAll importable modules passed! ✓")
        if expected_failures:
            print(f"({len(expected_failures)} modules have expected failures due to Django dependencies)")
        sys.exit(0)


if __name__ == "__main__":
    main()
