import logging

from django.contrib.auth.hashers import UNUSABLE_PASSWORD_PREFIX, UNUSABLE_PASSWORD_SUFFIX_LENGTH, get_hashers_by_algorithm, identify_hasher, make_password
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext as _

from ansible_base.activitystream.models import AuditableModel
from ansible_base.lib.abstract_models.common import CommonModel
from ansible_base.lib.abstract_models.user import AbstractDABUser
from ansible_base.lib.managers.user import UserUnmanagedManager
from ansible_base.lib.utils.models import user_summary_fields
from ansible_base.resource_registry.fields import AnsibleResourceField

logger = logging.getLogger('ansible_base.django_template.models.user')


def password_is_hashed(password):
    """
    Returns a boolean of whether password is hashed with loaded algorithms
    """
    if password is None:
        return False
    try:
        hasher = identify_hasher(password)
    except ValueError:
        # hasher can't be identified or is not loaded
        return False
    return hasher.algorithm in get_hashers_by_algorithm().keys()


def password_is_usable(password):
    """
    Returns True if password is None or wasn't generated by django.contrib.auth.hashers.make_password(None)
    """
    unusable_password_len = len(UNUSABLE_PASSWORD_PREFIX) + UNUSABLE_PASSWORD_SUFFIX_LENGTH

    # what are the odds that a user password starts with unusable prefix and the same length :-?
    return password is None or not (password.startswith(UNUSABLE_PASSWORD_PREFIX) and len(password) == unusable_password_len)


class AbstractTemplateUser(AbstractDABUser, CommonModel, AuditableModel):
    class Meta(AbstractUser.Meta):
        abstract = True

    ignore_relations = [
        'groups',  # not using the auth app stuff, see Team model
        'user_permissions',  # not using auth app permissions
        'logentry',  # used for Django admin pages, not the API
        'social_auth',  # Social auth endpoint
        'organizations_administered',  # We are going to merge [teams|orgs] the user is an admin in with [teams|orgs] the user is a member of
        'teams_administered',
    ]
    activity_stream_excluded_field_names = ['last_login']

    encrypted_fields = ()  # handed as special case by UserSerializer
    PASSWORD_FIELDS = ["password"]  # Mark password fields so ansible_base.lib.rest_filters can properly block attempts to filter over password

    resource = AnsibleResourceField(primary_key_field="id")

    managed = models.BooleanField(
        editable=False,
        blank=False,
        default=False,
        help_text=_("Indicates if this user is managed by the system. It cannot be modified once created."),
    )

    # By default, skip managed users (use all_objects for all users queryset)
    objects = UserUnmanagedManager()

    def __init__(self, *args, is_platform_auditor=False, **kwargs):
        super().__init__(*args, **kwargs)
        if is_platform_auditor:
            self._is_platform_auditor = True
        # Store the original value of the fields to check for field changes later
        self._original_fields = self._get_fields()

    def _get_fields(self):
        """
        Return a dictionary of the model's instance fields and their current values.
        """
        return {field.name: self.__dict__.get(field.name) for field in self._meta.fields}

    def save(self, *args, **kwargs):
        # If the password is empty string lets make it None, this will get turned into an unusable password by make_password
        if self.password == '':
            self.password = None

        if password_is_usable(self.password) and not password_is_hashed(self.password):
            self.password = make_password(self.password)

        super().save(*args, **kwargs)

    def summary_fields(self):
        return user_summary_fields(self)

    @property
    def organizations(self):

        from ansible_base.lib.utils.auth import get_organization_model
        if get_organization_model(return_none_on_error=True) is None:
            raise AttributeError("Property not available")
        else:
            return get_organization_model().access_qs(self, 'member')
