# Generated by Django 4.2.7 on 2024-01-26 14:25

from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import migrations


def create_system_user(apps, schema_editor):
    """
    Create the system user using the username in settings.

    The user is self-referential in its created_by and modified_by fields.
    It is inactive, only used for attributing internal changes to the system.
    """
    User = get_user_model()
    system_username = settings.SYSTEM_USERNAME
    if not User.objects.filter(username=system_username).exists():
        # Avoid using .create_user() here because it'll call save and we can't
        # pass in our non_existent_user_fatal arg.
        system_user = User(username=system_username, is_active=False)
        system_user.save(non_existent_user_fatal=False)
        system_user.created_by = system_user
        system_user.modified_by = system_user
        system_user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_set_up_resources_test_data'),
    ]

    operations = [
        migrations.RunPython(create_system_user),
    ]
