# Generated by Django 4.2.8 on 2024-01-16 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_app', '0002_team_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('organization__name', 'name')},
        ),
        migrations.RemoveField(
            model_name='organization',
            name='teams',
        ),
        migrations.AddField(
            model_name='team',
            name='created_by',
            field=models.ForeignKey(default=None, editable=False, help_text='The user who created this resource', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_created+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='created_on',
            field=models.DateTimeField(default=None, editable=False, help_text='The date/time this resource was created'),
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, default='', help_text='The team description.'),
        ),
        migrations.AddField(
            model_name='team',
            name='modified_by',
            field=models.ForeignKey(default=None, editable=False, help_text='The user who last modified this resource', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_modified+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='modified_on',
            field=models.DateTimeField(default=None, editable=False, help_text='The date/time this resource was created'),
        ),
        migrations.AddField(
            model_name='team',
            name='organization',
            field=models.ForeignKey(default=1, help_text='The organization of this team.', on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='test_app.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(help_text='The name of this resource', max_length=512),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('organization', 'name')},
        ),
    ]
