# Generated by Django 4.2.8 on 2024-03-12 00:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_create_system_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encryptionmodel',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='encryptionmodel',
            name='modified_on',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='modified_on',
        ),
        migrations.RemoveField(
            model_name='relatedfieldstestmodel',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='relatedfieldstestmodel',
            name='modified_on',
        ),
        migrations.RemoveField(
            model_name='team',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='team',
            name='modified_on',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='user',
            name='modified_on',
        ),
        migrations.AddField(
            model_name='encryptionmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date/time this resource was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encryptionmodel',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The date/time this resource was created'),
        ),
        migrations.AddField(
            model_name='organization',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date/time this resource was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The date/time this resource was created'),
        ),
        migrations.AddField(
            model_name='relatedfieldstestmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date/time this resource was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relatedfieldstestmodel',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The date/time this resource was created'),
        ),
        migrations.AddField(
            model_name='team',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date/time this resource was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The date/time this resource was created'),
        ),
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date/time this resource was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The date/time this resource was created'),
        ),
    ]
