# Generated by Django 4.2.8 on 2024-03-14 14:23

import ansible_base.lib.abstract_models.common
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_create_system_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmutableLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=None, editable=False, help_text='The date/time this resource was created')),
                ('message', models.CharField(max_length=400)),
                ('created_by', models.ForeignKey(default=None, editable=False, help_text='The user who created this resource', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_created+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(ansible_base.lib.abstract_models.common.ImmutableModel, models.Model),
        ),
    ]
