# Generated by Django 4.2.11 on 2024-07-17 14:46

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0012_encryptionjsonmodel'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='manageduser',
            managers=[
                ('all_objects', django.contrib.auth.models.UserManager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('all_objects', django.contrib.auth.models.UserManager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
