# Generated by Django 4.2.11 on 2024-09-05 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0016_organization_extra_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThingSomeoneShares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thing', models.CharField(max_length=256)),
                ('owner', models.ManyToManyField(related_name='things_i_share', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThingSomeoneOwns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thing', models.CharField(max_length=256)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='things_i_own', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'thing')},
            },
        ),
    ]
