# Generated by Django 5.2.9 on 2026-09-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0018_alter_animal_created_alter_animal_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, default='')),
                ('slug', models.SlugField(blank=True, default='', max_length=128)),
            ],
        ),
    ]
