# Generated by Django 5.2.9 on 2026-06-13 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0018_alter_animal_created_alter_animal_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceWithAdminPerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_perm_resources', to='test_app.organization')),
            ],
            options={
                'ordering': ['id'],
                'permissions': [('administrate_resourcewithadminperm', 'Can manage role assignments on this resource')],
            },
        ),
    ]
