# Generated by Django 5.2.9 on 2026-06-29 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0019_resourcewithadminperm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcewithadminperm',
            options={'ordering': ['id'], 'permissions': [('administrate_resourcewithadminperm', 'Can manage role assignments on this resource'), ('bop_resourcewithadminperm', 'Can bop this resource'), ('twist_resourcewithadminperm', 'Can twist this resource')]},
        ),
    ]
