# Generated by Django 4.2.8 on 2024-02-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dab_activitystream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='operation',
            field=models.CharField(choices=[('create', 'Entity created'), ('update', 'Entity updated'), ('delete', 'Entity deleted'), ('associate', 'Entity was associated with another entity'), ('disassociate', 'Entity was disassociated with another entity')], max_length=12),
        ),
    ]
