# Generated by Django 4.2.8 on 2024-04-07 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dab_activitystream', '0002_alter_entry_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='changes',
        ),
        migrations.CreateModel(
            name='FieldChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('operation', models.CharField(choices=[('added', 'Field added'), ('changed', 'Field changed'), ('removed', 'Field removed')], max_length=7)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='dab_activitystream.entry')),
            ],
            options={
                'verbose_name_plural': 'Field changes',
            },
        ),
    ]
