# Generated by Django 4.2.7 on 2024-02-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dab_resource_registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_hash',
            field=models.CharField(db_index=True, max_length=64, null=True),
        )
    ]
