#  Copyright 2024 Red Hat, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# Generated by Django 4.2.6 on 2024-03-01 18:41

from django.db import migrations, models

import ansible_base.resource_registry.models.resource


def reset_service_id(apps, schema_editor):
    ServiceID = apps.get_model("dab_resource_registry", "ServiceID")
    Resource = apps.get_model("dab_resource_registry", "Resource")
    Resource.objects.all().update(service_id=ServiceID.objects.first().id)


class Migration(migrations.Migration):

    dependencies = [
        ('dab_resource_registry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='resource_id',
            new_name='ansible_id',
        ),
        migrations.AlterField(
            model_name='resource',
            name='service_id',
            field=models.CharField(max_length=38),
        ),
        migrations.RunPython(
            code=reset_service_id,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='resource',
            name='service_id',
            field=models.UUIDField(default=ansible_base.resource_registry.models.resource.service_id),
        ),
    ]
