#  Copyright 2024 Red Hat, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# Generated by Django 4.2.8 on 2024-03-29 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dab_resource_registry', '0003_alter_resource_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcetype',
            name='migrated',
        ),
    ]
