# Generated by Django 4.2.10 on 2024-04-17 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dab_resource_registry', '0004_remove_resourcetype_migrated'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
