# Generated by Django 5.2.14 on 2026-05-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dab_resource_registry', '0007_alter_resource_ansible_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='resource',
            name='dab_resourc_content_6d9d9c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id'), include=('ansible_id',), name='unique_resource_content_type_object_id'),
        ),
    ]
