# Generated by Django 5.2.9 on 2026-05-29 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dab_resource_registry', '0008_resource_covering_index_ansible_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['id']},
        ),
    ]
