# Generated by Django 4.2.5 on 2023-10-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticator',
            name='order',
            field=models.IntegerField(default=1, help_text='The order in which an authenticator will be tried. This only pertains to username/password authenticators'),
        ),
    ]
