# Generated by Django 4.2.5 on 2023-10-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_base', '0003_authenticatoruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticatoruser',
            name='last_login',
            field=models.DateTimeField(default=None, editable=False, help_text='The date/time this user last logged in', null=True),
        ),
    ]
