# Generated by Django 4.2.5 on 2023-10-18 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_base', '0004_authenticatoruser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticator',
            name='category',
            field=models.CharField(default=None, help_text='The base type of this authenticator', max_length=30),
        ),
        migrations.AddField(
            model_name='authenticator',
            name='slug',
            field=models.SlugField(default=None, editable=False, help_text='An immutable identifier for the authenticator', max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='authenticatoruser',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authenticator_user', to='ansible_base.authenticator', to_field='slug'),
        ),
    ]
