# Generated by Django 4.2.5 on 2023-10-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_base', '0005_authenticator_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticatoruser',
            name='access_allowed',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='authenticatoruser',
            name='claims',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='authenticatoruser',
            name='last_login_map_results',
            field=models.JSONField(default=list),
        ),
    ]
