# Generated by Django 4.2.5 on 2023-10-20 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_base', '0006_user_tracking_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authenticatoruser',
            name='last_login',
        ),
    ]
