# Generated by Django 4.2.5 on 2023-11-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_base', '0007_remove_authenticatoruser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticatormap',
            name='name',
            field=models.CharField(help_text='The name of this resource', max_length=512, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authenticatormap',
            name='role',
            field=models.CharField(default=None, help_text='A role name this rule works on', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='authenticatormap',
            name='map_type',
            field=models.CharField(choices=[('team', 'team'), ('is_superuser', 'is_superuser'), ('is_system_auditor', 'is_system_auditor'), ('allow', 'allow'), ('role', 'role'), ('organization', 'organization')], default='team', help_text='What does the map work on, a team, a user flag or is this an allow rule', max_length=17),
        ),
    ]
