# Generated by Django 4.2.5 on 2023-11-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_base', '0007_remove_authenticatoruser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticatormap',
            name='name',
            field=models.CharField(help_text='The name of this resource', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authenticatormap',
            name='map_type',
            field=models.CharField(choices=[('team', 'team'), ('is_superuser', 'is_superuser'), ('is_system_auditor', 'is_system_auditor'), ('allow', 'allow'), ('organization', 'organization')], default='team', help_text='What does the map work on, a team, a user flag or is this an allow rule', max_length=17),
        ),
        migrations.AlterUniqueTogether(
            name='authenticatormap',
            unique_together={('name', 'authenticator')},
        ),
        migrations.AddConstraint(
            model_name='authenticatormap',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('map_type', 'organization'), _negated=True), ('organization__isnull', False), _connector='OR'), name='ansible_base_authenticatormap_require_org_if_org_map'),
        ),
    ]
