# Generated by Django 4.2.5 on 2023-11-10 22:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ansible_base', '0008_authenticatormap_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('externally_managed', models.BooleanField()),
                ('content_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resource_type', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(default=None, null=True)),
                ('ansible_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('resource_hash', models.CharField(max_length=512, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='contenttypes.contenttype')),
                ('parents', models.ManyToManyField(related_name='children', to='ansible_base.resource')),
            ],
            options={
                'unique_together': {('content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_permission', to='ansible_base.resourcetype')),
            ],
            options={
                'unique_together': {('resource_type', 'action')},
            },
        ),
    ]
