# Generated by Django 4.2.5 on 2023-12-12 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ansible_base', '0008_authenticatormap_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticator',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
