# Generated by Django 4.2.5 on 2023-11-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_base', '0008_authenticatormap_name_authenticatormap_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticatormap',
            name='name',
            field=models.CharField(help_text='The name of this resource', max_length=512),
        ),
        migrations.AlterUniqueTogether(
            name='authenticatormap',
            unique_together={('name', 'authenticator')},
        ),
        migrations.AddConstraint(
            model_name='authenticatormap',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('map_type', 'organization'), _negated=True), ('organization__isnull', False), _connector='OR'), name='ansible_base_authenticatormap_require_org_if_org_map'),
        ),
        migrations.AddConstraint(
            model_name='authenticatormap',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('map_type', 'role'), _negated=True), ('role__isnull', False), _connector='OR'), name='ansible_base_authenticatormap_require_role_if_role_map'),
        ),
    ]
