# Generated by Django 4.2.5 on 2023-12-06 17:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


def create_service_id(apps, schema_editor):
    ServiceID = apps.get_model("ansible_base", "ServiceID")
    if not ServiceID.objects.exists():
        ServiceID.objects.create()


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ansible_base', '0008_authenticatormap_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceID',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('externally_managed', models.BooleanField()),
                ('migrated', models.BooleanField(default=False)),
                ('resource_type', models.CharField(max_length=256)),
                ('content_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resource_type', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.TextField()),
                ('_service_id', models.UUIDField(null=True)),
                ('ansible_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('name', models.CharField(max_length=256, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='ansible_bas_content_62dd8a_idx')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
        migrations.RunPython(
            code=create_service_id,
            reverse_code=migrations.RunPython.noop
        ),
    ]
