# Generated by Django 4.2.5 on 2023-12-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_base', '0009_serviceid_resourcetype_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostgresTransaction',
            fields=[
                ('transaction', models.BigIntegerField(primary_key=True, serialize=False)),
                ('gid', models.CharField(max_length=200)),
                ('prepared', models.DateTimeField()),
            ],
            options={
                'db_table': 'pg_prepared_xacts',
                'managed': False,
            },
        ),
    ]
