# Generated by Django 4.2.5 on 2024-01-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_base', '0009_authenticator_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticator',
            name='type',
            field=models.CharField(editable=False, help_text='The type of authentication service this is', max_length=256),
        ),
    ]
