# Generated by Django 4.2.11 on 2024-10-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(editable=False, help_text='Name of the feature', unique=True)),
                ('description', models.TextField(editable=False, help_text='A description of the feature')),
                ('short_name', models.TextField(editable=False, help_text='A unique short name used to reference the feature', max_length=128, unique=True)),
                ('status', models.CharField(choices=[('a', 'Alpha'), ('b', 'Beta')], default='a', editable=False, help_text='The development status of the feature', max_length=1)),
                ('requires_restart', models.BooleanField(default=False, editable=False, help_text='Does changing the statue of this feature require a restart?')),
                ('enabled', models.BooleanField(default=False, help_text='Is this feature enabled')),
            ],
        ),
    ]
