import pytest
from django import VERSION
from django.contrib.contenttypes.models import ContentType
from django.db.models import F

from ansible_base.rbac.models import RoleDefinition, RoleUserAssignment
from ansible_base.rbac.permission_registry import permission_registry
from ansible_base.resource_registry.models import Resource, ResourceType
from test_app.models import Inventory, Organization


@pytest.mark.django_db
def test_resource_field_select_related(organization, organization_1, organization_2, django_assert_num_queries):
    org_ctype = ContentType.objects.get_for_model(Organization)

    with django_assert_num_queries(1) as captured:
        org_qs = Organization.objects.select_related("resource").all()
        org_names = set([org.name for org in org_qs])

    assert "dab_resource_registry_resource" in captured[0]["sql"]

    resource_qs = Resource.objects.filter(content_type=org_ctype)

    assert len(org_qs) > 2
    assert len(org_qs) == len(resource_qs)

    with django_assert_num_queries(0):
        org_resource_names = set([org.resource.name for org in org_qs])

    org_pks = set([str(org.pk) for org in org_qs])
    org_ansible_ids = set([org.resource.ansible_id for org in org_qs])

    resource_names = set([resource.name for resource in resource_qs])
    resource_object_ids = set([resource.object_id for resource in resource_qs])
    resource_ansible_ids = set([resource.ansible_id for resource in resource_qs])

    assert org_names == resource_names
    assert org_names == org_resource_names
    assert org_pks == resource_object_ids
    assert org_ansible_ids == resource_ansible_ids

    for org in org_qs:
        assert org.resource.pk == Resource.objects.get(object_id=org.pk, content_type=org_ctype).pk


@pytest.mark.django_db
def test_resource_field_prefetch_related(organization, organization_1, organization_2, django_assert_num_queries):
    org_ctype = ContentType.objects.get_for_model(Organization)

    with django_assert_num_queries(2) as captured:
        org_qs = list(Organization.objects.prefetch_related("resource").all())

    assert "dab_resource_registry_resource" not in captured[0]["sql"]
    assert "dab_resource_registry_resource" in captured[1]["sql"]

    resource_qs = Resource.objects.filter(content_type=org_ctype)

    assert len(org_qs) > 2
    assert len(org_qs) == len(resource_qs)

    # check that calling org.resource doesn't incur any further queries
    with django_assert_num_queries(0):
        org_resource_names = set([org.resource.name for org in org_qs])

    org_names = set([org.name for org in org_qs])
    org_pks = set([str(org.pk) for org in org_qs])
    org_ansible_ids = set([org.resource.ansible_id for org in org_qs])

    resource_names = set([resource.name for resource in resource_qs])
    resource_object_ids = set([resource.object_id for resource in resource_qs])
    resource_ansible_ids = set([resource.ansible_id for resource in resource_qs])

    assert org_names == resource_names
    assert org_names == org_resource_names
    assert org_pks == resource_object_ids
    assert org_ansible_ids == resource_ansible_ids

    for org in org_qs:
        assert org.resource.pk == Resource.objects.get(object_id=org.pk, content_type=org_ctype).pk


@pytest.mark.django_db
def test_resource_field_get(organization):
    """
    Test that <resource_model>.resource returns the correct Resource object.
    """
    resource = Resource.objects.get(object_id=organization.pk, content_type=ContentType.objects.get_for_model(organization))

    assert organization.resource.ansible_id == resource.ansible_id
    assert organization.name == organization.resource.name
    assert str(organization.pk) == resource.object_id
    assert organization.resource.pk == resource.pk


@pytest.mark.django_db
def test_resource_field_filtering(organization):
    """
    Test that queryset filter works.
    """
    resource = Resource.objects.get(object_id=organization.pk, content_type=ContentType.objects.get_for_model(organization))

    org = Organization.objects.get(resource__ansible_id=resource.ansible_id)
    assert org.resource.pk == resource.pk

    org = Organization.objects.get(resource__name=organization.name)
    assert org.resource.pk == resource.pk


@pytest.mark.django_db
def test_resource_field_prefetch_related_across_foreign_key(organization, organization_1, organization_2, django_assert_num_queries):
    """
    Generated by Claude Code (claude-sonnet-4-5@20250929)
    Test that prefetch_related works across a ForeignKey to a model with a resource field.
    This tests prefetching organization__resource on Inventory objects.
    """
    # Create inventory objects linked to organizations
    Inventory.objects.create(name="Inventory 1", organization=organization)
    Inventory.objects.create(name="Inventory 2", organization=organization_1)
    Inventory.objects.create(name="Inventory 3", organization=organization_2)

    org_ctype = ContentType.objects.get_for_model(Organization)

    # Prefetch organization__resource should result in 3 queries:
    # 1. Fetch all Inventory objects
    # 2. Fetch all related Organization objects
    # 3. Fetch all related Resource objects
    with django_assert_num_queries(3) as captured:
        inventory_qs = list(Inventory.objects.prefetch_related("organization__resource").all())

    # Verify the queries were as expected
    assert "test_app_inventory" in captured[0]["sql"]
    assert "test_app_organization" in captured[1]["sql"]
    assert "dab_resource_registry_resource" in captured[2]["sql"]

    assert len(inventory_qs) == 3

    # Collect resource pks for later verification
    resource_pks = {}
    with django_assert_num_queries(0):
        for inv in inventory_qs:
            assert inv.organization is not None
            assert inv.organization.resource is not None
            # Verify the resource data is correct
            assert inv.organization.name == inv.organization.resource.name
            assert str(inv.organization.pk) == inv.organization.resource.object_id
            resource_pks[inv.organization.pk] = inv.organization.resource.pk

    # Verify the resources match what's in the database
    for org_pk, resource_pk in resource_pks.items():
        expected_resource = Resource.objects.get(object_id=org_pk, content_type=org_ctype)
        assert resource_pk == expected_resource.pk


@pytest.mark.django_db
def test_resource_field_prefetch_resource_type_from_organization(organization, organization_1, organization_2, django_assert_num_queries):
    """
    Generated by Claude Code (claude-sonnet-4-5@20250929)
    Test that prefetch_related works from Organization through resource to resource_type.
    This tests prefetching resource__content_type__resource_type on Organization objects.
    """
    org_ctype = ContentType.objects.get_for_model(Organization)

    # Prefetch resource__content_type__resource_type should result in 4 queries:
    # 1. Fetch all Organization objects
    # 2. Fetch all related Resource objects
    # 3. Fetch all related ContentType objects
    # 4. Fetch all related ResourceType objects
    with django_assert_num_queries(4) as captured:
        org_qs = list(Organization.objects.prefetch_related("resource__content_type__resource_type").all())

    # Verify the queries were as expected
    assert "test_app_organization" in captured[0]["sql"]
    assert "dab_resource_registry_resource" in captured[1]["sql"]
    assert "django_content_type" in captured[2]["sql"]
    assert "dab_resource_registry_resourcetype" in captured[3]["sql"]

    assert len(org_qs) > 2

    # Collect resource type data for later verification
    resource_type_data = {}
    with django_assert_num_queries(0):
        for org in org_qs:
            assert org.resource is not None
            assert org.resource.content_type is not None
            assert org.resource.content_type.resource_type is not None
            # Verify the resource type is correct
            resource_type = org.resource.content_type.resource_type
            assert resource_type.content_type == org_ctype
            resource_type_data[org.pk] = resource_type.pk

    # Verify the resource types match what's in the database
    expected_resource_type = ResourceType.objects.get(content_type=org_ctype)
    for org_pk, resource_type_pk in resource_type_data.items():
        assert resource_type_pk == expected_resource_type.pk


@pytest.mark.django_db
def test_assignment_resource_field_f_annotation(admin_user, organization):
    """Test that F('resource__ansible_id') produces a JOIN-based annotation on assignment models."""
    org_ct = ContentType.objects.get_for_model(Organization)
    org_resource = Resource.objects.get(object_id=str(organization.pk), content_type=org_ct)
    rd = RoleDefinition.objects.create_from_permissions(
        name='test-org-view',
        permissions=['view_organization'],
        content_type=permission_registry.content_type_model.objects.get_for_model(Organization),
    )
    rd.give_permission(admin_user, organization)

    qs = RoleUserAssignment.objects.filter(user=admin_user, role_definition=rd).annotate(_ansible_id=F('resource__ansible_id'))
    assignment = qs.first()
    assert assignment is not None
    assert str(assignment._ansible_id) == str(org_resource.ansible_id)


@pytest.mark.django_db
def test_assignment_resource_field_select_related(admin_user, organization):
    """Test select_related('resource') on assignment models."""
    org_ct = ContentType.objects.get_for_model(Organization)
    org_resource = Resource.objects.get(object_id=str(organization.pk), content_type=org_ct)
    rd = RoleDefinition.objects.create_from_permissions(
        name='test-org-view-sr',
        permissions=['view_organization'],
        content_type=permission_registry.content_type_model.objects.get_for_model(Organization),
    )
    rd.give_permission(admin_user, organization)

    qs = RoleUserAssignment.objects.filter(user=admin_user, role_definition=rd).select_related('resource')
    assignment = qs.first()
    assert assignment is not None
    assert assignment.resource is not None
    assert assignment.resource.ansible_id == org_resource.ansible_id


@pytest.mark.django_db
def test_assignment_resource_field_lazy_access(admin_user, organization):
    """Test lazy instance access on assignment.resource (exercises get_extra_descriptor_filter)."""
    org_ct = ContentType.objects.get_for_model(Organization)
    org_resource = Resource.objects.get(object_id=str(organization.pk), content_type=org_ct)
    rd = RoleDefinition.objects.create_from_permissions(
        name='test-org-view-lazy',
        permissions=['view_organization'],
        content_type=permission_registry.content_type_model.objects.get_for_model(Organization),
    )
    rd.give_permission(admin_user, organization)

    assignment = RoleUserAssignment.objects.filter(user=admin_user, role_definition=rd).first()
    assert assignment.resource.ansible_id == org_resource.ansible_id


@pytest.mark.django_db
def test_assignment_resource_field_null_object(admin_user):
    """Test that system-wide assignments (no content_type/object_id) return None for resource."""
    rd = RoleDefinition.objects.create_from_permissions(
        name='test-global-view',
        permissions=['view_organization'],
        content_type=None,
    )
    rd.give_global_permission(admin_user)

    assignment = RoleUserAssignment.objects.filter(user=admin_user, role_definition=rd).select_related('resource').first()
    assert assignment is not None
    assert assignment.resource is None


@pytest.mark.django_db
def test_assignment_resource_excluded_from_summary_fields(admin_user, organization):
    """Test that resource is excluded from summary_fields via ignore_relations."""
    rd = RoleDefinition.objects.create_from_permissions(
        name='test-org-view-sf',
        permissions=['view_organization'],
        content_type=permission_registry.content_type_model.objects.get_for_model(Organization),
    )
    rd.give_permission(admin_user, organization)

    assignment = RoleUserAssignment.objects.filter(user=admin_user, role_definition=rd).first()
    assert 'resource' in type(assignment).ignore_relations
    summary = assignment.get_summary_fields()
    assert 'resource' not in summary


@pytest.mark.skipif(VERSION[0] < 5, reason='get_prefetch_querysets() is only valid for Django 5+')
@pytest.mark.django_db
@pytest.mark.parametrize(
    "querysets_arg",
    [
        pytest.param([Resource.objects.none(), Resource.objects.none()], id="two_querysets"),
        pytest.param([Resource.objects.none(), Resource.objects.none(), Resource.objects.none()], id="three_querysets"),
    ],
)
def test_resource_field_get_prefetch_querysets_invalid_length(organization, querysets_arg):
    """
    Generated by Claude Code (claude-sonnet-4-5@20250929)
    Test that get_prefetch_querysets raises ValueError when querysets argument has invalid length.
    The method expects exactly 1 queryset if querysets is provided, so multiple querysets should raise.
    """
    # Get the forward descriptor for the resource field
    descriptor = Organization.resource.field.forward_related_accessor_class(Organization.resource.field)

    # Call get_prefetch_querysets with invalid querysets argument
    with pytest.raises(ValueError, match='querysets argument of get_prefetch_querysets\\(\\) should have a length of 1\\.'):
        descriptor.get_prefetch_querysets([organization], querysets=querysets_arg)
