# Generated by Django 4.2.11 on 2024-05-06 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dab_resource_registry', '0004_remove_resourcetype_migrated'),
        ('dab_rbac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleteamassignment',
            name='resource',
            field=models.ForeignKey(help_text='A UUID identifier of the object this role assignment applies to, null value may indicate system-wide role or a model that has no ansible_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_object_assignments', to='dab_resource_registry.resource'),
        ),
        migrations.AddField(
            model_name='roleteamassignment',
            name='user_resource',
            field=models.ForeignKey(help_text='A UUID identifier of the team given permission defined by this assignment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_team_assignments', to='dab_resource_registry.resource'),
        ),
        migrations.AddField(
            model_name='roleuserassignment',
            name='resource',
            field=models.ForeignKey(help_text='A UUID identifier of the object this role assignment applies to, null value may indicate system-wide role or a model that has no ansible_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_object_assignments', to='dab_resource_registry.resource'),
        ),
        migrations.AddField(
            model_name='roleuserassignment',
            name='user_resource',
            field=models.ForeignKey(help_text='A UUID identifier of the user given permission defined by this assignment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_user_assignments', to='dab_resource_registry.resource'),
        ),
        migrations.AddField(
            model_name='objectrole',
            name='resource',
            field=models.ForeignKey(help_text='A UUID identifier of the object this role assignment applies to, null value may indicate system-wide role or a model that has no ansible_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_object_assignments', to='dab_resource_registry.resource'),
        ),
    ]
