# Generated by Django 4.2.23 on 2025-06-30 12:48

from django.db import migrations

from . import _utils


class Migration(migrations.Migration):

    dependencies = [
        ('dab_rbac', '0004_remote_permissions_additions'),
    ]

    operations = [
        migrations.RunPython(_utils.create_types_if_needed, migrations.RunPython.noop),
        migrations.RunPython(_utils.migrate_content_type, migrations.RunPython.noop),
    ]
