# Generated by Django 5.2.9 on 2026-08-05 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dab_rbac', '0009_unique_global_assignments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.ANSIBLE_BASE_TEAM_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='roleteamassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('object_role__isnull', True)), fields=('team', 'role_definition'), name='unique_global_team_assignment'),
        ),
        migrations.AddConstraint(
            model_name='roleuserassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('object_role__isnull', True)), fields=('user', 'role_definition'), name='unique_global_user_assignment'),
        ),
    ]
