# Generated by Claude Sonnet 4
from ansible_base.lib.management.advisory_locks import AdvisoryLocksCommand


class Command(AdvisoryLocksCommand):
    """Management command to show active PostgreSQL advisory locks."""

    pass
