---
name: CI
on:
  pull_request:
  push:
jobs:
  tox:
    name: django-ansible-base - ${{ matrix.tests.env }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        tests:
          - env: py39
            python-version: "3.9"
            sonar: false
          - env: py310
            python-version: "3.10"
            sonar: false
          - env: py311
            python-version: "3.11"
            sonar: true
    steps:
      - uses: actions/checkout@v3

      - name: Install build requirements
        run: sudo apt-get update && sudo apt-get install -y libsasl2-dev libldap2-dev libssl-dev

      - name: Install python ${{ matrix.tests.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.tests.python-version }}

      - name: Install tox
        run: pip${{ matrix.tests.python-version }} install tox

      - name: Run tox
        run: tox -e ${{ matrix.tests.env }}

      - name: Inject PR number into coverage.xml
        if: matrix.tests.sonar
        run: sed -i '2i <!-- PR ${{ github.event.number }} -->' coverage.xml

      - name: Upload coverage as artifact
        uses: actions/upload-artifact@v2
        if: matrix.tests.sonar
        with:
          name: coverage
          path: coverage.xml

      - name: SonarCloud Scan (on push)
        uses: SonarSource/sonarcloud-github-action@master
        if: matrix.tests.sonar && github.event_name == 'push' && github.repository == 'ansible/django-ansible-base'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
