---
name: Testing DAB Consumers
on:
  push:
    branches:
      - devel
      - "stable-*"
  pull_request:
jobs:
  hub:
    name: hub
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
          path: django-ansible-base 

      - name: install system dependencies
        run: |
          sudo apt update
          sudo apt install -y libsasl2-dev libldap2-dev libssl-dev gettext

      - uses: actions/checkout@v4
        with:
          repository: ansible/galaxy_ng
          path: hub

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install tox
        run: pip install tox

      - name: Run Hub unit tests
        working-directory: hub
        run: |
          pwd
          echo "--ls -la--"
          ls -la
          echo "--ls -la ../--"
          ls -la ../
          echo "--tox--"
          tox -e py312
          .tox/py312/bin/pip show galaxy-ng
          .tox/py312/bin/pip show django-ansible-base
