---
name: Testing DAB Consumers
on:
  push:
    branches:
      - devel
      - "stable-*"
  pull_request:
jobs:
  hub:
    name: hub
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
          path: django-ansible-base 

      - uses: actions/checkout@v4
        with:
          repository: ansible/galaxy_ng
          path: hub

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install tox
        run: pip install tox

      - name: Run Hub unit tests
        working-directory: hub
        run: |
          pwd
          ls -la

          tox -e py312

