---
name: DVCS (Find Jira Key)
on:
  pull_request_target:
jobs:
  dvcs_pr_checker:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    name: Check the PR for DVCS integration
    steps:
      - uses: ansible/dvcs-action@0106255aa32ffdefe91475fe98db51116807a9a6 # v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
