---
name: Linting
env:
  LC_ALL: "C.UTF-8" # prevent ERROR: Ansible could not initialize the preferred locale: unsupported locale setting
on:
  pull_request:
  push:
jobs:
  common-tests:
    name: ${{ matrix.tests.name }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        tests:
          - name: api-flake8
            command: check_flake8
          - name: api-black
            command: check_black
          - name: api-isort
            command: check_isort
    steps:
      - name: Install make
        run: sudo apt install make

      - uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Install python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install requirments
        run: pip3.11 install -r requirements/requirements_dev.txt

      - name: Run check ${{ matrix.tests.name }}
        run: make ${{ matrix.tests.command }}
