---
name: Release django-ansible-base

env:
  LC_ALL: "C.UTF-8" # prevent ERROR: Ansible could not initialize the preferred locale: unsupported locale setting
  PROJECT_NAME: django-ansible-base

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout dab
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          show-progress: false

      - name: Get python version from Makefile
        run: echo py_version=`make PYTHON_VERSION` >> $GITHUB_ENV

      - name: Install python ${{ env.py_version }}
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ env.py_version }}

      - name: Install python deps
        run: pip install -r requirements/requirements_dev.txt

      - name: Build the dists
        run: >-
          ansible-playbook
          tools/ansible/release.yml
          -i localhost
          -e github_token="$GITHUB_TOKEN"
          -t build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Store the distribution packages
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: python-package-distributions
          path: |
            dist/*.tar.gz
            dist/*.whl
          retention-days: 90

  publish-pypi:
    name: Publish to PyPI
    needs:
      - build

    runs-on: ubuntu-latest

    timeout-minutes: 1

    environment:
      name: pypi
      url: https://pypi.org/project/${{ env.PROJECT_NAME }}

    permissions:
      contents: read  # This job doesn't need to `git push` anything
      id-token: write  # PyPI Trusted Publishing (OIDC)

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish dists to PyPI
        uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247 # v1.14.1

  post-release-repo-update:
    name: Make a GitHub Release
    needs:
      - publish-pypi

    runs-on: ubuntu-latest

    timeout-minutes: 2

    permissions:
      packages: write
      contents: write

    steps:
      - name: Checkout dab
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          show-progress: false

      - name: Download all the dists
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: python-package-distributions
          path: dist/

      - name: Get python version from Makefile
        run: echo py_version=`make PYTHON_VERSION` >> $GITHUB_ENV

      - name: Install python ${{ env.py_version }}
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ env.py_version }}

      - name: Install python deps
        run: pip install -r requirements/requirements_dev.txt

      - name: Create a GitHub Release uploading the dists
        run: >-
          ansible-playbook
          tools/ansible/release.yml
          -i localhost
          -e github_token="$GITHUB_TOKEN"
          -t github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
